name: Trigger Deploy Terraform Repo
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
 GITHUB_TOKEN: ${{ secrets.ACTIONS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub CLI trigger command
        run: |
          gh workflow run Deploy_Production --repo https://github.com/LugsoIn2/cad-terraform-all.git --ref main
