name: Trigger Deploy Terraform Repo
on:
  push:
    branches:
      - main
  workflow_dispatch:
     inputs:
      which_workflow:
        description: 'Ù‹Workflow on Terraform Repo which will triggered'
        required: true
        default: 'deploy_production.yml'

      which_branch:
        description: 'Which branch'
        required: true
        default: 'main'

env:
 GITHUB_TOKEN: ${{ secrets.ACTIONS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub CLI trigger command
        run: |
          gh run list --workflow=${{ github.event.inputs.which_workflow }} --ref ${{ github.event.inputs.which_branch }}
